# domain.crd.yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: clientsecurityconfigs.stable.patricelabs.io
spec:
  # group name to use for clientsecurityconfig: /clientsecurityconfig/<group>/<version>
  group: stable.patricelabs.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              required: [clientId,pinningType]
              type: object
              properties:
                metadata:
                  type: object
                  properties:
                    owner:
                      type: string
                clientId:
                  type: string
                audience:
                  type: string 
                pinningType:
                  type: string
                  enum: [SRP,cookie,cert]
                accessTokenTTL:
                  type: integer
                refreshTokenTTL:
                  type: integer
                domain:
                  type: object
                  properties:
                    name:
                      type: string
                
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /clientsecurityconfig/<group>/<version>/<plural>
    plural: clientsecurityconfigs
    # singular name to be used as an alias on the CLI and for display
    singular: clientsecurityconfig
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: clientSecurityConfig
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - csc
