# domain.crd.yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: domains.stable.patricelabs.io
spec:
  # group name to use for domains: /domains/<group>/<version>
  group: stable.patricelabs.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              required: [domainBase,domainGroups]
              type: object
              properties:
                metadata:
                  type: object
                  properties:
                    owner:
                      type: string
                domainBase:
                  type: string
                domainGroups:
                  type: array
                  items:
                    type: object
                    properties:
                      groupType: 
                        type: string
                      environments:
                        type: array
                        items:
                          type: object
                          properties:
                            envName:
                              type: string
                            fullDomain:
                              type: string
                            fixedAppForDomain:
                              type: string
                            appToRedirectOnRoot:
                              type: string
                
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /domains/<group>/<version>/<plural>
    plural: domains
    # singular name to be used as an alias on the CLI and for display
    singular: domain
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: domain
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - dom
