# microservice.crd.yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: microservices.stable.patricelabs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.patricelabs.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                subscriptions:
                  type: array
                  items:
                    type: object # API endpoint
                    properties:
                      method:
                        type: string
                      host:
                        type: string
                      pathTemplate:
                        type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: microservices
    # singular name to be used as an alias on the CLI and for display
    singular: microservice
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Microservice
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
     - msrv
     - msvc
